export const STATIONS = [
  'Mosson',
  'Hall Jules Guesde',
  'Saint Paul',
  'Les Bouisses',
  'Celleneuve',
  'Tonnelles',
  'Jules Guesde',
  'La Martelle',
  'Pergola',
  "Château d'Ô",
  'Malbosc',
  'Euromédecine',
  'Hôpital Lapeyronie',
  'Occitanie',
  'Saint Eloi',
  'Universités',
  'Plan Cabanes',
  'Saint Denis',
  'Comédie',
  'Corum',
  'Les Aubes',
  'Pompignane',
  'Moulares',
  'Port Marianne',
  "Place de l'Europe",
  'Rives du Lez',
  'Antigone',
  'Léon Blum',
  'Millénaire',
  'La Galine',
  'Notre-Dame de Sablassou',
  'Jacou',
];
